symbols:
  - 1000BONK
  - 1000PEPE
  - 1000SHIB
  - AAVE
  - ARB
  - AVAX
  - BCH
  - BIO
  - BNB
  - BOME
  - BTC
  - CRV
  - DOGE
  - ENA
  - ETH
  - ETHFI
  - FIL
  - HBAR
  - LINK
  - LTC
  - NEAR
  - NEO
  - ORDI
  - PNUT
  - SOL
  - SUI
  - TIA
  - UNI
  - WIF
  - WLFI
  - WLD
  - XRP
  -
days: 180
