delay_pair: 5
delay_symbol: 10

symbols:
  - 1000BONK
  - 1000PEPE
  - 1000SHIB
  - AAVE
  - ADA
  - ARB
  - AVAX
  - BCH
  - BIO
  - BNB
  - BOME
  - BTC
  - CRV
  - DOGE
  - ENA
  - ETHFI
  - ETH
  - FIL
  - HBAR
  - KAIT
  - LINK
  - LTC
  - NEAR
  - NEO
  - ORDI
  - PENGU
  - PNUT
  - SOL
  - SUI
  - TIA
  - TRUMP
  - UNI
  - WIF
  - WLD
  - WLFI
  - XRP

days: 730
